package com.example.LMS.constant;

public enum CourseCategory {
    WEB_DEVELOPMENT,
    BACKEND_DEVELOPMENT,
    FRONTEND_DEVELOPMENT,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    ARTIFICIAL_INTELLIGENCE,
    MOBILE_DEVELOPMENT,
    CLOUD_COMPUTING,
    DEVOPS,
    CYBER_SECURITY,
    GAME_DEVELOPMENT,
    SOFTWARE_ENGINEERING,
    IOT
}
